### ISSUE TITLE
ohai >= 4.0.0 throws nillclass on node['ohai']['plugin_path']

### ISSUE THREAD

**Issue by hrak** [priestjim/chef-openresty#47]
ohai cookbook version 4.0.0 was released yesterday, which has breaking changes that are not compatible with this cookbook.

The main issue is that the ohai cookbook now uses a custom resource, and no longer defines attributes like node['ohai']['plugin_path'], which is used in this cookbook in recipes/ohai_plugin.rb.

The issue can be solve by pinning ohai to ~> 3.0.1 or < 4.0.0 or something similar.

**Comment by hulu1522** [comment]
👍 

This needs to be fixed.  Here is the warnings that are thrown:

```
[2016-05-20T17:56:42+00:00] WARN: Ohai::Config[:plugin_path] is set. Ohai::Config[:plugin_path] is deprecated and will be removed in future releases of ohai. Use ohai.plugin_path in your configuration file to configure :plugin_path for ohai.
[2016-05-20T17:56:42+00:00] WARN: [DEPRECATION] Plugin at /etc/chef/ohai_plugins/nginx.rb is a version 6 plugin. Version 6 plugins will not be supported in future releases of Ohai. Please upgrade your plugin to version 7 plugin syntax. For more information visit here: docs.chef.io/ohai_custom.html
[2016-05-20T17:56:42+00:00] WARN: Ohai::Mixin::Command run_command is deprecated and will be removed in Ohai 9.0.0
[2016-05-20T17:56:42+00:00] WARN: Ohai::Mixin::Command popen4 is deprecated and will be removed in Ohai 9.0.0
```

And if using on updated ohai cookbooks:

```
* ohai[reload_nginx] action reload[2016-05-20T17:50:09+00:00] ERROR: Encountered error while running plugins: #<Ohai::Exceptions::AttributeNotFound: No such attribute: 'nginx'>
       
           
           ================================================================================
           Error executing action `reload` on resource 'ohai[reload_nginx]'
           ================================================================================
           
           Ohai::Exceptions::AttributeNotFound
           -----------------------------------
           No such attribute: 'nginx'
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:49:in `block in run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:47:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:47:in `run_action'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/openresty/recipes/ohai_plugin.rb
           
            23: ohai 'reload_nginx' do
            24:   action :nothing
            25:   plugin 'nginx'
            26: end
            27: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/openresty/recipes/ohai_plugin.rb:23:in `from_file'
           
           ohai("reload_nginx") do
             action [:nothing]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             plugin "nginx"
             declared_type :ohai
             cookbook_name "openresty"
             recipe_name "ohai_plugin"
           end
           
           Platform:
           ---------
           x86_64-linux
```

**Comment by priestjim** [comment]
I've fixed it and also upgraded the Ohai plugin to version 7. I'll commit and push when the Chef maintainers merge and release the newest version of the Ohai cookbook with support for templates which this cookbook needs.
