### ISSUE TITLE
getting a "ChecksumMismatch" exception from pcre download

### ISSUE THREAD

**Issue by dorongutman** [priestjim/chef-openresty#56]
I can't install openresty due to this exception.

```
Chef::Exceptions::ChecksumMismatch
----------------------------------
Checksum on resource (b9e02d) does not match checksum on content (818a4b)

Cookbook Trace:
---------------
/var/chef/runs/855ccda3-34bf-4b73-98ce-cdc269a3f086/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

Resource Declaration:
---------------------
# In /var/chef/runs/855ccda3-34bf-4b73-98ce-cdc269a3f086/local-mode-cache/cache/cookbooks/openresty/recipes/commons_build.rb

 77:   remote_file "#{pcre_path}.tar.bz2" do
 78:     owner 'root'
 79:     group 'root'
 80:     mode 00644
 81:     source node['openresty']['pcre']['url']
 82:     checksum node['openresty']['pcre']['checksum']
 83:     action :create
 84:   end
 85:   execute 'openresty-extract-pcre' do

Compiled Resource:
------------------
# Declared in /var/chef/runs/855ccda3-34bf-4b73-98ce-cdc269a3f086/local-mode-cache/cache/cookbooks/openresty/recipes/commons_build.rb:77:in `from_file'

remote_file("/var/chef/runs/855ccda3-34bf-4b73-98ce-cdc269a3f086/local-mode-cache/cache/pcre-8.38.tar.bz2") do
  provider Chef::Provider::RemoteFile
  action [:create]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  source ["https://sourceforge.net/projects/pcre/files/pcre/8.38/pcre-8.38.tar.bz2/download"]
  use_etag true
  use_last_modified true
  declared_type :remote_file
  cookbook_name "openresty"
  recipe_name "commons_build"
  checksum "b9e02d36e23024d6c02a2e5b25204b3a4fa6ade43e0a5f869f254f49535079df"
  path "/var/chef/runs/855ccda3-34bf-4b73-98ce-cdc269a3f086/local-mode-cache/cache/pcre-8.38.tar.bz2"
  owner "root"
  group "root"
  mode 420
end

Platform:
---------
x86_64-linux
```

**Comment by dorongutman** [comment]
this seems to be related to issues sourceforge is having right now - https://twitter.com/sfnet_ops/status/752962244200189952
